"""Phase 16.8 inventory-only Python documentation facts.

No candidate formulations are stored here. Fact keys and locations were
checked against the official documentation pages linked in each row.
"""
from __future__ import annotations

from datetime import date

from codeguard.ml.phase16_7_facts import LICENSE, LICENSE_URL, REVIEW_STATUS

# key, topic, URL, title, section, locator, paraphrased evidence, canonical fact
ROWS = [
    ("import_cache_none_blocks", "import system", "https://docs.python.org/3/reference/import.html", "The import system", "The module cache", "§5.3.1 The module cache", "If a module name maps to None in sys.modules, import raises ModuleNotFoundError.", "A sys.modules entry whose value is None causes an import of that name to raise ModuleNotFoundError."),
    ("import_reload_same_object", "import system", "https://docs.python.org/3/reference/import.html", "The import system", "The module cache", "§5.3.1 The module cache", "importlib.reload reuses the existing module object and reruns its code.", "importlib.reload() reinitializes a module by rerunning its code in the same module object."),
    ("import_reimport_new_object", "import system", "https://docs.python.org/3/reference/import.html", "The import system", "The module cache", "§5.3.1 The module cache", "Removing a module cache entry and importing again can create a distinct module object while old references remain.", "Deleting a module's sys.modules entry and importing it again can produce a different module object from one still held elsewhere."),
    ("import_parent_first", "modules and packages", "https://docs.python.org/3/reference/import.html", "The import system", "Searching", "§5.3 Searching", "A dotted import attempts the parent module/package before the requested submodule; a failed intermediate import raises ModuleNotFoundError.", "Importing a dotted name searches its parent components before the final submodule."),
    ("import_module_cached_before_exec", "import system", "https://docs.python.org/3/reference/import.html", "The import system", "Loading", "§5.4 Loading", "The module is placed in sys.modules before its code executes to prevent unbounded recursion during self-import.", "Python inserts a module into sys.modules before executing its code, which supports recursive imports."),
    ("import_failure_remove_only_failed", "import system", "https://docs.python.org/3/reference/import.html", "The import system", "Loading", "§5.4 Loading", "On load failure the failing module is removed from sys.modules, while cached modules and successfully loaded side-effect modules remain.", "A failed import removes the failing module's cache entry without removing other already-loaded modules."),
    ("descriptor_get_instance_binding", "descriptors and attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Invoking Descriptors", "§3.3.2.3 Invoking Descriptors — Instance Binding", "Instance access to descriptor x on a uses type(a).__dict__['x'].__get__(a, type(a)).", "Instance binding invokes a descriptor's __get__ with the instance and its type."),
    ("descriptor_class_binding", "descriptors and attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Invoking Descriptors", "§3.3.2.3 Invoking Descriptors — Class Binding", "Class access A.x invokes A.__dict__['x'].__get__(None, A).", "Class binding invokes a descriptor's __get__ with None as the instance and the owner class as the owner."),
    ("descriptor_data_over_instance_dict", "descriptors and attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Invoking Descriptors", "§3.3.2.3 Invoking Descriptors", "Data descriptors with __set__ or __delete__ take precedence over an instance-dictionary redefinition.", "A data descriptor takes precedence over an attribute with the same name in an instance dictionary."),
    ("descriptor_nondata_overridable", "descriptors and attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Invoking Descriptors", "§3.3.2.3 Invoking Descriptors", "A non-data descriptor can be overridden by an instance attribute.", "An instance attribute can override a non-data descriptor of the same name."),
    ("descriptor_property_data_descriptor", "descriptors", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Invoking Descriptors", "§3.3.2.3 Invoking Descriptors", "property() is implemented as a data descriptor.", "The property() function implements a data descriptor."),
    ("descriptor_getattr_only_on_failure", "attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Customizing Attribute Access", "§3.3.2.2 Customizing Attribute Access — __getattr__", "__getattr__ is called when normal attribute lookup fails with AttributeError, not when normal lookup succeeds.", "An instance's __getattr__ is invoked only after ordinary attribute access fails with AttributeError."),
    ("descriptor_getattribute_unconditional", "attribute access", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Customizing Attribute Access", "§3.3.2.2 Customizing Attribute Access — __getattribute__", "__getattribute__ is called unconditionally for instance attribute accesses.", "A class-defined __getattribute__ handles every ordinary instance attribute access."),
    ("special_method_lookup_bypasses_getattribute", "data model and special methods", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Special method lookup", "§3.3 Special method lookup", "Implicit special-method invocation may bypass instance __getattribute__.", "Implicit special-method lookup can bypass an object's __getattribute__ implementation."),
    ("comparison_returns_notimplemented", "comparison behavior", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Rich comparison methods", "§3.3.1.1 Rich comparison methods", "Rich comparison methods may return NotImplemented for operand pairs they do not handle.", "A rich comparison method can return NotImplemented when it does not implement a comparison for the operands."),
    ("comparison_boolean_context_calls_bool", "comparison behavior", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Rich comparison methods", "§3.3.1.1 Rich comparison methods", "Comparison methods may return non-bool values; Boolean contexts convert the result with bool().", "When a rich-comparison result is used as a condition, Python applies bool() to it."),
    ("comparison_equal_hash_required", "object model and hashing", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Emulating numeric types", "§3.3.1 Basic customization — __hash__", "Objects that compare equal are required to have equal hash values.", "If two objects compare equal, their hash values must be equal."),
    ("comparison_default_object_eq_identity", "comparison behavior", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Rich comparison methods", "§3.3.1.1 Rich comparison methods", "object's default __eq__ compares identity and returns NotImplemented when identities differ.", "The default object.__eq__ treats an object as equal to itself and otherwise returns NotImplemented."),
    ("iterator_next_stopiteration", "iterator protocol", "https://docs.python.org/3/library/stdtypes.html", "Built-in Types", "Iterator Types", "Iterator Types", "An iterator's __next__ returns the next value or raises StopIteration when exhausted.", "An exhausted iterator signals completion by raising StopIteration from __next__()."),
    ("iterator_exhaustion_sticky", "iterator protocol", "https://docs.python.org/3/library/stdtypes.html", "Built-in Types", "Iterator Types", "Iterator Types", "Once an iterator raises StopIteration, subsequent __next__ calls should continue raising StopIteration.", "An iterator that has raised StopIteration is expected to keep raising it on subsequent next calls."),
    ("generator_call_returns_iterator", "generators", "https://docs.python.org/3/reference/expressions.html", "Expressions", "Yield expressions", "§6.2.8 Yield expressions — Generator functions", "Calling a generator function returns a generator iterator; its body starts when a generator method is called.", "Calling a generator function creates a generator iterator without immediately running its body."),
    ("generator_yield_suspends_state", "generators", "https://docs.python.org/3/reference/expressions.html", "Expressions", "Yield expressions", "§6.2.8 Yield expressions — Generator functions", "At yield suspension, local bindings, instruction position, evaluation stack, and exception state are retained.", "A suspended generator retains its local execution state until it resumes."),
    ("generator_send_sets_yield_expression", "generators", "https://docs.python.org/3/reference/expressions.html", "Expressions", "Yield expressions", "§6.2.8.3 Generator-iterator methods", "send(value) resumes a suspended generator and makes the yield expression evaluate to value.", "Sending a value into a suspended generator supplies that value as the result of its paused yield expression."),
    ("generator_close_raises_generatorexit", "generators", "https://docs.python.org/3/reference/expressions.html", "Expressions", "Yield expressions", "§6.2.8.3 Generator-iterator methods — close()", "close() raises GeneratorExit at the suspension point and lets the generator clean up.", "Calling generator.close() injects GeneratorExit at its suspension point to terminate it and run cleanup."),
    ("async_iter_aiter_returns_iterator", "asynchronous iteration", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Asynchronous Iterators", "§3.4.3 Asynchronous Iterators — __aiter__", "__aiter__ must return an asynchronous iterator object.", "An asynchronous iterable's __aiter__ method must return an asynchronous iterator."),
    ("async_iter_anext_awaitable", "asynchronous iteration", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Asynchronous Iterators", "§3.4.3 Asynchronous Iterators — __anext__", "__anext__ must return an awaitable for the next value and should raise StopAsyncIteration at completion.", "An asynchronous iterator's __anext__ returns an awaitable and signals exhaustion with StopAsyncIteration."),
    ("async_iter_aiter_typeerror_noniterator", "asynchronous iteration", "https://docs.python.org/3/reference/datamodel.html", "Data model", "Asynchronous Iterators", "§3.4.3 Asynchronous Iterators", "Since Python 3.7, __aiter__ returning something other than an asynchronous iterator results in TypeError.", "Under the current asynchronous iteration protocol, __aiter__ returning a non-iterator causes TypeError."),
    ("contextmanager_exactly_one_yield", "context managers", "https://docs.python.org/3/library/contextlib.html", "Utilities for with-statement contexts", "contextmanager", "contextmanager()", "A generator decorated with contextmanager must yield exactly one value.", "A generator used by contextlib.contextmanager must yield exactly one value for the with statement."),
    ("contextmanager_body_exception_injected", "context managers and exceptions", "https://docs.python.org/3/library/contextlib.html", "Utilities for with-statement contexts", "contextmanager", "contextmanager()", "An unhandled exception from the with body is reraised inside the generator at the yield point.", "contextlib.contextmanager injects an exception from the with body at the generator's yield point."),
    ("contextmanager_reraise_logged_exception", "context managers and exceptions", "https://docs.python.org/3/library/contextlib.html", "Utilities for with-statement contexts", "contextmanager", "contextmanager()", "If a contextmanager generator catches an exception only to log or act, it must reraise it or the with statement treats it as handled.", "A contextmanager generator that catches an exception without suppressing it must reraise it."),
    ("contextmanager_single_use", "context managers", "https://docs.python.org/3/library/contextlib.html", "Utilities for with-statement contexts", "Single use, reusable and reentrant context managers", "Single use, reusable and reentrant context managers", "Context managers created by contextmanager are single use; reusing one can raise RuntimeError because its generator did not yield.", "A contextlib.contextmanager instance is single-use and cannot be entered a second time."),
    ("subprocess_run_completedprocess", "subprocess", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "run", "Using the subprocess Module — run()", "run waits for completion and returns a CompletedProcess object.", "subprocess.run() waits for the command to complete and returns a CompletedProcess."),
    ("subprocess_check_nonzero_raises", "subprocess and exceptions", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "run", "Using the subprocess Module — run(check=True)", "With check=True, a nonzero process exit raises CalledProcessError.", "subprocess.run(check=True) raises CalledProcessError when the child exits with a nonzero status."),
    ("subprocess_timeout_kills_child", "subprocess", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "run", "Using the subprocess Module — timeout", "If run's timeout expires, the child is killed and waited for before TimeoutExpired is reraised.", "When subprocess.run() times out, it kills and waits for the child before raising TimeoutExpired."),
    ("subprocess_capture_output_conflicts_streams", "subprocess", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "run", "Using the subprocess Module — capture_output", "capture_output sets stdout and stderr to PIPE and cannot be combined with stdout or stderr arguments.", "subprocess.run(capture_output=True) cannot be used together with explicit stdout or stderr arguments."),
    ("subprocess_env_replaces_inherited", "subprocess and environment", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "run", "Using the subprocess Module — env", "Supplying env passes the specified environment mapping instead of inheriting the parent's default environment.", "The env argument to subprocess.run supplies the child environment in place of normal environment inheritance."),
    ("subprocess_communicate_pipe_deadlock_avoid", "subprocess and file objects", "https://docs.python.org/3/library/subprocess.html", "Subprocess management", "Popen objects", "Popen.wait() and Popen.communicate()", "wait can deadlock with PIPE streams if output fills the OS pipe buffer; communicate is recommended.", "When using subprocess pipes, communicate() avoids the pipe-buffer deadlock risk associated with wait()."),
    ("path_read_text_closed", "pathlib and file I/O", "https://docs.python.org/3/library/pathlib.html", "Object-oriented filesystem paths", "Reading and writing files", "Reading and writing files — read_text()", "read_text returns decoded contents as str and closes the file after reading.", "Path.read_text() returns decoded text and closes the opened file."),
    ("path_write_text_overwrites", "pathlib and file I/O", "https://docs.python.org/3/library/pathlib.html", "Object-oriented filesystem paths", "Reading and writing files", "Reading and writing files — write_text()", "write_text opens in text mode, writes data, closes the file, and overwrites an existing same-name file.", "Path.write_text() overwrites an existing file at that path."),
    ("path_resolve_symlinks_absolute", "pathlib", "https://docs.python.org/3/library/pathlib.html", "Object-oriented filesystem paths", "Resolving", "Path.resolve()", "resolve returns a new absolute path and resolves symlinks.", "Path.resolve() returns a new absolute path with symbolic links resolved."),
    ("path_relative_to_lexical", "pathlib", "https://docs.python.org/3/library/pathlib.html", "Object-oriented filesystem paths", "Pure paths", "PurePath.relative_to()", "relative_to is lexical and raises ValueError for incompatible anchors.", "PurePath.relative_to() performs a lexical path operation and raises ValueError when anchors are incompatible."),
    ("itertools_batched_lazy", "itertools and iterators", "https://docs.python.org/3/library/itertools.html", "Itertools", "itertools functions", "itertools.batched()", "batched consumes only enough input to form the next tuple and yields batches lazily.", "itertools.batched() consumes its input lazily, only as needed to form each output batch."),
    ("itertools_batched_last_short", "itertools", "https://docs.python.org/3/library/itertools.html", "Itertools", "itertools functions", "itertools.batched()", "The final tuple from batched may contain fewer than n elements.", "itertools.batched() can yield a final tuple shorter than the requested batch size."),
    ("itertools_accumulate_initial_extra", "itertools", "https://docs.python.org/3/library/itertools.html", "Itertools", "itertools functions", "itertools.accumulate()", "When initial is supplied, accumulate yields the initial value first and produces one more output than input elements.", "itertools.accumulate(initial=...) yields one more item than the input iterable."),
    ("itertools_tee_buffering", "itertools and iterators", "https://docs.python.org/3/library/itertools.html", "Itertools", "itertools functions", "itertools.tee()", "tee may require significant auxiliary storage depending on how far its output iterators diverge.", "itertools.tee() may need significant temporary storage when its returned iterators advance at different rates."),
    ("dataclass_eq_identical_type", "dataclasses", "https://docs.python.org/3/library/dataclasses.html", "Data Classes", "dataclass parameters", "dataclass() — eq parameter", "Generated dataclass equality compares fields as a tuple and requires identical instance types.", "Generated dataclass __eq__ compares field tuples only when both objects have the identical type."),
    ("dataclass_order_requires_eq", "dataclasses and comparison", "https://docs.python.org/3/library/dataclasses.html", "Data Classes", "dataclass parameters", "dataclass() — order parameter", "order=True with eq=False raises ValueError.", "A dataclass configured with order=True and eq=False raises ValueError."),
    ("dataclass_frozen_not_truly_immutable", "dataclasses and mutability", "https://docs.python.org/3/library/dataclasses.html", "Data Classes", "Frozen instances", "Frozen instances", "frozen=True emulates immutability via generated setters that raise FrozenInstanceError; Python objects are not made truly immutable.", "dataclasses.frozen=True emulates immutability but does not make an instance truly immutable."),
    ("dataclass_inherited_field_order", "dataclasses and inheritance", "https://docs.python.org/3/library/dataclasses.html", "Data Classes", "Inheritance", "Inheritance", "Dataclass fields are collected from base classes in reverse MRO before subclass fields; subclass fields override base fields.", "Dataclass field order is based on reverse-MRO base fields followed by subclass fields, with subclass definitions overriding inherited fields."),
    ("enum_iter_excludes_aliases", "enum", "https://docs.python.org/3/library/enum.html", "Enum", "Supported data types", "How are Enums different? / iteration", "Iterating an enum yields canonical members and omits aliases.", "Iteration over an Enum excludes alias names."),
    ("enum_members_includes_aliases", "enum", "https://docs.python.org/3/library/enum.html", "Enum", "Supported data types", "How are Enums different? / __members__", "__members__ is a read-only ordered mapping that includes aliases.", "An enum's __members__ mapping includes aliases and is read-only and ordered."),
    ("enum_value_call_name_index", "enum", "https://docs.python.org/3/library/enum.html", "Enum", "Programmatic access", "Programmatic access", "Enum call syntax looks up a member by value; indexing looks it up by name.", "EnumClass(value) performs by-value lookup, while EnumClass[name] performs by-name lookup."),
    ("enum_ordered_comparisons_not_supported", "enum and comparison", "https://docs.python.org/3/library/enum.html", "Enum", "Comparisons", "Comparisons", "Ordinary Enum members do not support ordered comparisons.", "Members of a plain Enum do not support ordering comparisons such as less-than."),
    ("typing_runtime_no_enforcement", "typing and runtime behavior", "https://docs.python.org/3/library/typing.html", "Typing", "Type hints", "Type Hints", "The Python runtime does not enforce function and variable annotations.", "Function and variable type annotations are not enforced by the Python runtime."),
    ("typing_annotated_metadata_ignored", "typing", "https://docs.python.org/3/library/typing.html", "Typing", "Annotated", "Annotated", "Tools without special handling for Annotated metadata should treat Annotated[T, x] as T.", "A tool with no special handling for Annotated metadata should treat Annotated[T, x] as its underlying type T."),
    ("logging_propagate_parent_handlers", "logging", "https://docs.python.org/3/library/logging.html", "Logging facility for Python", "Logger objects", "Logger.propagate", "When propagate is true, a logger's events are offered to handlers on its ancestor loggers up to root.", "A logger with propagate=True passes eligible records to ancestor logger handlers."),
    ("logging_propagate_false_stops", "logging", "https://docs.python.org/3/library/logging.html", "Logging facility for Python", "Logger objects", "Logger.propagate", "Propagation stops at the logger whose propagate attribute is false.", "A logger with propagate=False stops passing its records to ancestor handlers."),
    ("functools_lru_args_hashable", "functools", "https://docs.python.org/3/library/functools.html", "Functools", "lru_cache", "lru_cache()", "lru_cache uses a dictionary, so function arguments must be hashable.", "Arguments to an lru_cache-decorated function must be hashable."),
    ("functools_lru_threadsafe_duplicate_calls", "functools and threading", "https://docs.python.org/3/library/functools.html", "Functools", "lru_cache", "lru_cache()", "lru_cache's data structure is thread-safe, but concurrent calls may compute the same uncached value more than once.", "functools.lru_cache can invoke the wrapped function more than once for the same key during concurrent first calls."),
]

def facts() -> list[dict[str, str]]:
    today = date.today().isoformat()
    result = []
    for key, topic, url, title, section, locator, evidence, canonical in ROWS:
        group = f"page:{url}"
        result.append({
            "fact_id": key, "fact_key": key, "canonical_fact": canonical,
            "fact_statement": canonical, "topic": topic, "source_url": url,
            "source_title": title, "section": section,
            "evidence_locator": locator, "evidence_text": evidence,
            "license": LICENSE, "license_url": LICENSE_URL,
            "evidence_group": group, "source_group": group,
            "claim_family": key, "source_type": "official_python_documentation",
            "retrieval_date": today,
            "provenance_status": "Official Python documentation page checked; evidence paraphrased; independent review pending",
            "review_priority": "inventory_only_pending_review",
            "fact_review_status": REVIEW_STATUS,
        })
    return result
